site_name: My test
theme: 
    name: material
    custom-dir: overrides
    features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - anounce.dismiss
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer
