site_name: My Site
theme: 
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - anounce.dismiss
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer