site_name: My Docs
theme: 
    name: material
    custom-dir: overrides
    features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - anounce.dismiss
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.footer
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
